# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: src-python-docker-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: port5000
  selector:
    app: src-python-docker
