version: '3.8'
services:
  python-docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=1
      - VISION_KEY=97c1ed0586e94038b8ba331f3dda265c
      - VISION_ENDPOINT=https://python-ocr-computer-vision.cognitiveservices.azure.com/
